### ISSUE TITLE
AttributeError: 'module' object has no attribute 'WriteOpCtx'

### ISSUE THREAD

**Issue by tingzhonghuang** [pcuzner/ceph-iscsi-cli#156]
[root@standby1 tmp]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.7 (Maipo)
Release:        7.7
Codename:       Maipo
[root@standby1 tmp]# uname -a
Linux standby1 3.10.0-1062.el7.x86_64 #1 SMP Thu Jul 18 20:25:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

[root@standby1 tmp]# rpm -qa|grep ceph
python-cephfs-0.94.10-0.el7.x86_64
ceph-radosgw-0.94.10-0.el7.x86_64
ceph-common-0.94.10-0.el7.x86_64
ceph-0.94.10-0.el7.x86_64
ceph-deploy-1.5.37-0.noarch
ceph-iscsi-3.4-1.el7.noarch
libcephfs1-0.94.10-0.el7.x86_64

start rbd-target-api failed

[root@standby1 tmp]# systemctl status rbd-target-api
● rbd-target-api.service - Ceph iscsi target configuration API
   Loaded: loaded (/usr/lib/systemd/system/rbd-target-api.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Thu 2020-06-11 06:04:43 EDT; 19min ago
  Process: 4324 ExecStart=/usr/bin/rbd-target-api (code=exited, status=1/FAILURE)
 Main PID: 4324 (code=exited, status=1/FAILURE)

Jun 11 06:04:42 standby1 systemd[1]: rbd-target-api.service: main process exited, code=exited, status=1/FAILURE
Jun 11 06:04:42 standby1 systemd[1]: Unit rbd-target-api.service entered failed state.
Jun 11 06:04:42 standby1 systemd[1]: rbd-target-api.service failed.
Jun 11 06:04:43 standby1 systemd[1]: rbd-target-api.service holdoff time over, scheduling restart.
Jun 11 06:04:43 standby1 systemd[1]: Stopped Ceph iscsi target configuration API.
Jun 11 06:04:43 standby1 systemd[1]: start request repeated too quickly for rbd-target-api.service
Jun 11 06:04:43 standby1 systemd[1]: Failed to start Ceph iscsi target configuration API.
Jun 11 06:04:43 standby1 systemd[1]: Unit rbd-target-api.service entered failed state.
Jun 11 06:04:43 standby1 systemd[1]: rbd-target-api.service failed.

[root@standby1 tmp]# journalctl -e -u rbd-target-api

Jun 11 06:04:42 standby1 rbd-target-api[4324]: Traceback (most recent call last):
Jun 11 06:04:42 standby1 rbd-target-api[4324]: File "/usr/bin/rbd-target-api", line 2946, in <module>
Jun 11 06:04:42 standby1 rbd-target-api[4324]: config = Config(logger)
Jun 11 06:04:42 standby1 rbd-target-api[4324]: File "/usr/lib/python2.7/site-packages/ceph_iscsi_config/common.py", line 97, in __init__
Jun 11 06:04:42 standby1 rbd-target-api[4324]: if self.init_config():
Jun 11 06:04:42 standby1 rbd-target-api[4324]: File "/usr/lib/python2.7/site-packages/ceph_iscsi_config/common.py", line 430, in init_config
Jun 11 06:04:42 standby1 rbd-target-api[4324]: with rados.WriteOpCtx(ioctx) as op:
Jun 11 06:04:42 standby1 rbd-target-api[4324]: AttributeError: 'module' object has no attribute 'WriteOpCtx'
Jun 11 06:04:42 standby1 systemd[1]: rbd-target-api.service: main process exited, code=exited, status=1/FAILURE

**Comment by tingzhonghuang** [comment]
Jun 11 06:04:42 standby1 rbd-target-api[4324]: AttributeError: 'module' object has no attribute 'WriteOpCtx'

**Comment by tingzhonghuang** [comment]
[root@master ~]# rpm -qa|grep rados
python-rados-0.94.10-0.el7.x86_64
